### ISSUE TITLE
SSL library conflict

### ISSUE THREAD

**Issue by MBerka** [jllopis/docker-mosquitto#13]
Running the standard setup this morning,
`git init`

`git pull https://github.com/jllopis/docker-mosquitto`

`docker-compose up`

repeatedly produced the following error during the main RUN:

`ERROR: unsatisfiable constraints:
  openssl-dev-1.1.1a-r0:
    conflicts:
               libressl-dev-2.7.4-r2[pc:libcrypto=1.1.1a]
               libressl-dev-2.7.4-r2[pc:libssl=1.1.1a]
               libressl-dev-2.7.4-r2[pc:openssl=1.1.1a]
    satisfies:
               postgresql-dev-11.1-r0[openssl-dev]
               curl-dev-7.62.0-r2[openssl-dev]
               libssh2-dev-1.8.0-r4[pc:libcrypto]
               libssh2-dev-1.8.0-r4[pc:libssl]
  libressl-dev-2.7.4-r2:
    conflicts:
               openssl-dev-1.1.1a-r0[pc:libcrypto=2.7.4]
               openssl-dev-1.1.1a-r0[pc:libssl=2.7.4]
               openssl-dev-1.1.1a-r0[pc:openssl=2.7.4]
    satisfies: world[libressl-dev]
               libssh2-dev-1.8.0-r4[pc:libcrypto]
               libssh2-dev-1.8.0-r4[pc:libssl]`

So, conflicting SSL libraries. Since the Dockerfile does not mention openssl, I figured it might be a change in Alpine, since the version is unpinned. Changing it to `FROM alpine:3.8` allowed Docker to get through the dependency installation. It appears that Alpine has indeed been switching between openssl and libressl, though I am not clear how Edge would have this problem relative to 3.8, when the switch appears to be towards libre and this project is using libre. For your consideration.

**Comment by diogopms** [comment]
I'm having the same issue after changing to `alpine:3.8`

```
be-http.c: In function 'http_post':
be-http.c:136:22: error: argument to 'sizeof' in 'snprintf' call is the same expression as the destination; did you mean to provide an explicit length? [-Werror=sizeof-pointer-memaccess]
  snprintf(url, sizeof(url), "%s://%s:%d%s",
                      ^
cc1: all warnings being treated as errors
make: *** [<builtin>: be-http.o] Error 1
The command '/bin/sh -c buildDeps='git build-base libressl-dev libwebsockets-dev c-ares-dev util-linux-dev hiredis-dev postgresql-dev curl-dev libxslt docbook-xsl';     chmod +x /run.sh &&     mkdir -p /var/lib/mosquitto &&     touch /var/lib/mosquitto/.keep &&     mkdir -p /etc/mosquitto.d &&     apk update &&     apk add $buildDeps hiredis postgresql-libs libwebsockets libuuid c-ares libressl curl ca-certificates &&     git clone https://github.com/eclipse/mosquitto.git &&     cd mosquitto &&     git checkout ${MOSQUITTO_VERSION} -b ${MOSQUITTO_VERSION} &&     sed -i -e "s|(INSTALL) -s|(INSTALL)|g" -e 's|--strip-program=${CROSS_COMPILE}${STRIP}||' */Makefile */*/Makefile &&     sed -i "s@/usr/share/xml/docbook/stylesheet/docbook-xsl/manpages/docbook.xsl@/usr/share/xml/docbook/xsl-stylesheets-1.79.1/manpages/docbook.xsl@" man/manpage.xsl &&     sed -i 's/ -lanl//' config.mk &&     make WITH_MEMORY_TRACKING=no WITH_SRV=yes WITH_WEBSOCKETS=yes WITH_TLS_PSK=no &&     make install &&     git clone git://github.com/jpmens/mosquitto-auth-plug.git &&     cd mosquitto-auth-plug &&     cp config.mk.in config.mk &&     sed -i "s/BACKEND_REDIS ?= no/BACKEND_REDIS ?= yes/" config.mk &&     sed -i "s/BACKEND_HTTP ?= no/BACKEND_HTTP ?= yes/" config.mk &&     sed -i "s/BACKEND_MYSQL ?= yes/BACKEND_MYSQL ?= no/" config.mk &&     sed -i "s/BACKEND_POSTGRES ?= no/BACKEND_POSTGRES ?= yes/" config.mk &&     sed -i "s/BACKEND_JWT ?= no/BACKEND_JWT ?= yes/" config.mk &&     sed -i "s/MOSQUITTO_SRC =/MOSQUITTO_SRC = ..\//" config.mk &&     make &&     cp auth-plug.so /usr/local/lib/ &&     cp np /usr/local/bin/ && chmod +x /usr/local/bin/np &&     cd / && rm -rf mosquitto &&     apk del $buildDeps && rm -rf /var/cache/apk/*' returned a non-zero code: 2
```

Any news of this issue?

Thanks

**Comment by MBerka** [comment]
@diogopms Yes, I have seen your issue too. It is separate, since it only kicks in at `make`. As I did not want the HTTP backend, `sed -i "s/BACKEND_HTTP ?= no/BACKEND_HTTP ?= yes/" config.mk` was good enough for me. Since we're talking about it - it is from mosquitto-auth-plug. Someone reported it there (https://github.com/jpmens/mosquitto-auth-plug/issues/387) and a fix has already been pushed. Repeating my steps above currently produces the described dependency error, and no errors with the version pinned.

The fix feels a bit simple for a pull request, but I'll submit one unless someone has a deeper solution that keeps using alpine:edge.

**Comment by jllopis** [comment]
Alpine moved from openssl to libressl around [two years ago](http://lists.alpinelinux.org/alpine-devel/5463.html) but they seem to be moving back (http://lists.alpinelinux.org/alpine-devel/6334.html). So they are pushing changes to edge, hence the error. Will keep an eye on it.

Agree with pinning to `alpine:3.8` (@diogopms will merge your PR #14, thanks).
