### ISSUE TITLE
Cloning libwebsockets failed.

### ISSUE THREAD

**Issue by carolus-r** [jllopis/docker-mosquitto#15]
Could not compile with websockets as the repo was not found
https://libwebsockets.org/repo/libwebsockets

I replaced it with the new repo:
https://github.com/warmcat/libwebsockets

I successfully compiled but am I doing the right thing?

**Comment by jllopis** [comment]
I can not reproduce this. As far as I know, `https://libwebsockets.org/repo/libwebsockets' 
 is still the main repo as stated in [their web page](https://libwebsockets.org) (_Getting started_ section).

Does anybody else find this problem?

**Comment by ElizabethMorves** [comment]
I successfully compiled, but websockets not work. Maybe I missed something.

**Comment by smnvhn** [comment]
https://libwebsockets.org/repo/libwebsockets is not working for me as well!

**Comment by ElizabethMorves** [comment]
libwebsockel broken a long time ago. In new versions it is impossible to connect php script. I could not make friends with ssl. That was a few months ago. I managed to collect something satisfactorily working from old versions. I used warmcat libwebsocket 2.4.2 and something else. ッ
