### ISSUE TITLE
Websockets

### ISSUE THREAD

**Issue by natcl** [jllopis/docker-mosquitto#8]
I can't seem to get websockets to work at all, any special thing to do ?
I get this in the log:
`1495739241: Opening websockets listen socket on port 9883.`
But my clients seem to timeout.

**Comment by natcl** [comment]
I just tested the previous tag (1.4.10) and not problems with that version so something broke with websockets with version 1.4.11....

**Comment by natcl** [comment]
Further testing shows that websockets seems broken in alpine:3.5 which uses libwebsockets-dev 2.1.0 but works with alpine:edge which uses libwebsockets-dev 2.2.0

**Comment by jllopis** [comment]
Updated to v3.6 which also use libwebsockets-dev 2.2.0

**Comment by natcl** [comment]
Thanks works now !
